pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo '===start building image==='
                dir('./') {
                    sh 'docker build -t app .'
                }
            }
        }
        
        stage('Backup') {
            when {
                expression { currentBuild.resultIsBetterOrEqualTo('SUCCESS') }
            }
            steps {
                echo '====start creating backup===='
                script {
                   sh 'mkdir -p /var/lib/jenkins/workspace/Staging/backup-directory'
                }
                sh 'docker save app -o /var/lib/jenkins/workspace/Staging/backup-directory/app-artifact.tar'
                echo '====backup completed===='
            }
        }
        
    }
}
